### ISSUE TITLE
Злые слова в коде

### ISSUE THREAD

**Issue by mochalkinblues** [NikitaChampion/data-structures#5]
https://github.com/NikitaChampion/data-structures/blob/67a70ebe02a34c2d0c806e8e39c4559e906663ca/contest/hacks/bad-sort.cpp#L36

Добрый день, заметил ужаснейшие злые слова в вашем коде задачи. День стал плохим. Пожалуйста, уточните неслучайность этих скверных выражений, дабы миру спалось спокойней.

**Comment by NikitaChampion** [comment]
Не влияет на смысл задачи

**Comment by NikitaChampion** [comment]
И на русском это "Эта сортировка отстой\n"

**Comment by cooleck** [comment]
Мне все-таки, кажется, что данное высказывание можно также перевести как "Данная сортировка сосет", что уже наталкивает на другой подтекст

**Comment by NikitaChampion** [comment]
Если это так вас волнует, поменяю
